# Generated by Django 5.2 on 2025-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='unicode', max_length=10)),
                ('title', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('todo_type', models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')])),
            ],
        ),
    ]
